config/routes.rb
Rails.application.routes.draw do

  resources :buisnesses
  resources :people
  resources :relationships

  get 'welcome/index'

  root 'welcome#index'

end

app/models/buisness.rb
class Buisness < ActiveRecord::Base
#holds buisness name, location, products. see relationship for other variables
  require 'carrierwave'

  attr_accessor :image
  has_many :relationships
  has_many :people, through: :relationships
  mount_uploader :image, ImageUploader
end

app/models/person.rb
class Person < ActiveRecord::Base
#Model for people within the system, just holds name variable, all others found in relationships
  has_many :relationships
  has_many :buisnesses, through: :relationships
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
#relations within the system, hold the ids of the person and buisness, related salary and position information
  belongs_to :buisness
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buisnesses_controller.rb
class BuisnessesController < ApplicationController
#Controlls buisness related actions
  before_action :set_buisness, only: [:show, :edit, :update, :destroy]
  #before_action :set_uploader, :new

  # GET /buisnesses
  # GET /buisnesses.json
  def index
    @buisnesses = Buisness.all
  end

  # GET /buisnesses/1
  # GET /buisnesses/1.json
  def show
  end

  # GET /buisnesses/new
  def new
    @buisness = Buisness.new
  end

  # GET /buisnesses/1/edit
  def edit
  end

  # POST /buisnesses
  # POST /buisnesses.json
  def create
    @buisness = Buisness.new(buisness_params)

    respond_to do |format|
      if @buisness.save
        format.html { redirect_to @buisness, notice: 'Buisness was successfully created.' }
        format.json { render :show, status: :created, location: @buisness }
      else
        format.html { render :new }
        format.json { render json: @buisness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buisnesses/1
  # PATCH/PUT /buisnesses/1.json
  def update
    respond_to do |format|
      if @buisness.update(buisness_params)
        format.html { redirect_to @buisness, notice: 'Buisness was successfully updated.' }
        format.json { render :show, status: :ok, location: @buisness }
      else
        format.html { render :edit }
        format.json { render json: @buisness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buisnesses/1
  # DELETE /buisnesses/1.json
  def destroy
    @buisness.destroy
    respond_to do |format|
      format.html { redirect_to buisnesses_url, notice: 'Buisness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_buisness
      @buisness = Buisness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buisness_params
      params.require(:buisness).permit(:name, :location, :products, :image)
    end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
#controlls people related actions
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_buisnesses, only: [:show, :index]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def set_buisnesses
      @buisnesses = Buisness.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
#controlls relationship relation table
  before_action :set_buisnesses, only: [:create, :new, :edit]
  before_action :set_people, only: [:create, :new, :edit]

  def new
    @relationship = Relationship.new
  end

  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to buisnesses_path, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
  end

  private

    def relationship_params
      params.require(:relationship).permit(:buisness_id, :person_id, :relation)
    end

    def set_buisnesses
      @buisnesses = Buisness.all
    end

    def set_people
      @people = Person.all
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buisnesses_helper.rb
module BuisnessesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buisnesses/_form.html.erb
<%= form_for @buisness, html: {multipart: true} do |f| %>
  <% if @buisness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buisness.errors.count, "error") %> prohibited this buisness from being saved:</h2>

      <ul>
      <% @buisness.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :products %><br>
    <%= f.text_field :products %>
  </div>
  <p>
    <%= f.file_field :image %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buisnesses/edit.html.erb
<h1>Editing Buisness</h1>

<%= render 'form' %>

<%= link_to 'Show', @buisness %> |
<%= link_to 'Back', buisnesses_path %>

app/views/buisnesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buisnesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buisnesses.each do |buisness| %>
      <tr>
        <td><%= buisness.name %></td>
        <td><%= buisness.location %></td>
        <td><%= buisness.products %></td>
        <td><%= link_to 'Show', buisness %></td>
        <td><%= link_to 'Edit', edit_buisness_path(buisness) %></td>
        <td><%= link_to 'Destroy', buisness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buisness', new_buisness_path %>

app/views/buisnesses/new.html.erb
<h1>New Buisness</h1>

<%= render 'form' %>

<%= link_to 'Back', buisnesses_path %>

app/views/buisnesses/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @buisness.image_url(:thumb)%>

<p>
  <strong>Name:</strong>
  <%= @buisness.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @buisness.location %>
</p>

<p>
  <strong>Products:</strong>
  <%= @buisness.products %>
</p>

<p>
|| Relations ||
</p>

Managers
  <p>
    <% @buisness.people.each do |person|%>
      <% if person.relationships.map {|r| r.buisness == @buisness && r.relation == 'Manager' }.include?(true)%>
        <div>
          <p>
            <td><%= person.name %></td> |
            <td><%= link_to 'Show', person_path(person) %></td>
          </p>
        </div>
      <% end %>
    <% end %>
  </p>

Employees
<p>
  <% @buisness.people.each do |person|%>
    <% if person.relationships.map {|r| r.buisness == @buisness && r.relation == 'Employee' }.include?(true)%>
      <div>
        <p>
          <td><%= person.name %></td> |
          <td><%= link_to 'Show', person_path(person) %></td>
        </p>
      </div>
    <% end %>
  <% end %>
</p>

<%= link_to 'New Relation', new_relationship_path %> |
<%= link_to 'Edit', edit_buisness_path(@buisness) %> |
<%= link_to 'Back', buisnesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HasManyThroughManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>

        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Associations: </strong>

  <% @buisnesses.each do |buis| %>
    <p>
    <%= buis.name %>
    <%= link_to "Buisness Page", buis %>
    <p>
  <%end%>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buisness, "Buisness" %><br />
    <%= f.select :buisness_id, options_for_select(@buisnesses.map{|buisness| [buisness.name, buisness.id]}), {}%>
  </div>

  <div class="field">
    <%= f.label :person, "Employee" %><br />
    <%= f.select :person_id, options_for_select(@people.map{|person| [person.name, person.id]}), {}%>
  </div>

  <div class="field">
    <%= f.label :relation %><br>
    <%= f.select :relation, options_for_select(["Manager", "Employee", "Owner", "Contact"]) %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/new.html.erb
<h1>New Relation</h1>

<%= render 'form' %>

<%= link_to 'Back', buisnesses_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in views/welcome/index.html.erb</p>

<%= link_to 'Buisnesses', buisnesses_path %>